version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongoDBSem2"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/dbexit

    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  # uncomment to run backend on docker 
  # shart:
  #   build: .
  #   container_name: "shart"
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017/uade_sem2_shart
  #   volumes:
  #     - ./src:/home/app/src
  #   ports:
  #     - 9999:9999
