version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongoDBSem2"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/dbexit

    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
